version: "3.5"

services:
  xc-mysql-sakila-db:
     network_mode: host
     image: mysql:8.0
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
     volumes:
       - ./packages/nocodb/tests/mysql-sakila-db:/docker-entrypoint-initdb.d
  xc-cypress-nocodb:
    network_mode: host
    image: node:14-alpine
    environment:
      - EE=true
    volumes:
      - ./packages/nocodb:/home/app
    command:
      - /bin/sh
      - -c
      - |
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        # cp -r /home/app1/ /home/app/
        rm /home/app/package-lock.json
        rm /home/app/noco.db
        cd /home/app/ && npm i && EE=true npm run run
        # cd /home/app/ && npm i && EE=true npm run watch:run
  xc-cypress-nc-gui:
    network_mode: host
    image: node:14-alpine
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - EE=true
    volumes:
      - ./packages/nc-gui:/home/app
      - ./packages/nc-lib-gui:/home/nc-lib-gui
    command:
      - /bin/sh
      - -c
      - |
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        apk --update --no-cache add git
        # cp -r /home/app1/ /home/app/
        rm /home/app/package-lock.json
        # cd /home/app/ && npm i && npm run dev
        cd /home/app/ && npm i && NODE_ENV=development npm run build && npm start















