name: Node.js Package

on: push

jobs:
  publish-gpr:
    if: github.event.ref == 'refs/heads/nc-lib-gui'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17
          registry-url: https://npm.pkg.github.com/
      - run: echo $'@Deep-Consulting-Solutions:registry=https://npm.pkg.github.com/\n@deep-consulting-solutions:registry=https://npm.pkg.github.com/\nalways-auth=true\n//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' > .npmrc
      - run: |
          export NODE_OPTIONS="--max_old_space_size=16384"
          cd packages/nc-gui && npm install && npm run build:copy:publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
