name: "Publish : noco-i18n"

on:
  push:
    branches: [ master ]
    paths:
      - "packages/noco-i18n/**"
  release:
    types: [ published ]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build noco-i18n
        run: |
          cd packages/noco-i18n
          npm install
          npm run generate


      - name: Pushes generated output
        # uses: dmnemec/copy_file_to_another_repo_action@main
        uses: dmnemec/copy_file_to_another_repo_action@1b29cbd9a323185f20b175dc6d5f8f31be5c0658
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          clear_folder: 'docs/dist'
          source_file: 'packages/noco-i18n/dist/'
          destination_repo: 'nocodb/noco-i18n'
          destination_folder: 'docs'
          user_email: 'oof1lab@gmail.com'
          user_name: 'o1lab'
          commit_message: 'Autorelease from github.com/nocodb/nocodb/packages/noco-i18n'
