name: 'Sync changes to master branch from develop'

on:
  # Triggered manually
  workflow_dispatch:
  # Triggered by release-nocodb.yml
  workflow_call:
jobs:
  sync-to-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Merge from develop to master
        uses: wingkwong/gh-action-nightly-merge@master
        with:
          stable_branch: 'develop'
          development_branch: 'master'
          allow_ff: true
          allow_forks: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}