# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend Unit Tests

on:
  push:
    branches: ["develop"]
    paths:
      - "packages/nocodb/**"
  pull_request:
    branches: ["develop"]
    paths:
      - "packages/nocodb/**"

jobs:
  unit-tests:

    runs-on: [self-hosted, v4, generic]

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install dependencies nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: npm ci
      - name: build nocodb-sdk
        working-directory: ./packages/nocodb-sdk
        run: npm run build:main
      - name: install dependencies nocodb
        working-directory: ./packages/nocodb
        run: npm ci
      - name: run unit tests
        working-directory: ./packages/nocodb
        run: npm run unit-test
